layout_spectrum: 0.09235151531174779
typography_spectrum: 0.07283441699109972
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.5194601654075086
  lightness: 0.8705844318028539
  saturation: 0.6092814477160573
  rhythmicContrast: 0.34495301847346127
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Cleo
  email: cleo@stocksfamily.org
  url: cleo.stocksfamily.org
name: Cleo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: I'm a cat.
purpose: []
