name: Cleo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24538651295006275
title: Cleo Pat-Her
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1bcc0'
    - '#131313'
    - '#908c83'
    - '#684c34'
    - '#3d3936'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5856019672937691
  rhythmicContrast: 0.5
purpose: []
