typography_spectrum: 0.8528056261129677
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.023829450365155935
  lightness: 0.690654908074066
  saturation: 0.30544862034730613
  rhythmicContrast: 0.1863113169092685
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24558206531219184
analytics:
  google: null
  facebook: null
  twitter: null
name: Cleo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: I'm a cat.
purpose: []
